name = "course-tracker"
main = "src/index.js"
compatibility_date = "2023-01-20"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

[vars]
AIRTABLE_BASE_ID = "apphWeWmiGhwhIS4L"
AIRTABLE_TABLE_NAME = "test"
FORM_URL = "https://course-tracker.mdima4266.workers.dev"
AIRTABLE_URL='https://api.airtable.com/v0'
FORM_URL = "https://course-tracker-bdn.pages.dev/"